### ISSUE TITLE
make doesnt work, missing most of its files

### ISSUE THREAD

**Issue by wumbomumbo** [AlexeyGurevsky/bbtube#5]
title says it

**Comment by AlexeyGurevsky** [comment]
@saulcheeseman Hello. Unfortunately, I'm not a professional Linux / C++ developer who uses console and other tools on a daily basis. I remember that I used Momentics IDE and the build worked well. Probably, Momentics did all the job regarding make commands.
Since BB OS 10 is EOL now, as well as the BBTube app, I'm not going to do anything, sorry about that.
